package com.todo.model;

// Generated Jun 3, 2016 3:56:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer deptId;
	private String deptNm;
	private String createdBy;
	private Date createdDttm;
	private String updatedBy;
	private Date updatedDttm;
	private Set userDepts = new HashSet(0);
	private Set tasklists = new HashSet(0);

	public Department() {
	}

	public Department(String deptNm) {
		this.deptNm = deptNm;
	}

	public Department(String deptNm, String createdBy, Date createdDttm, String updatedBy, Date updatedDttm,
			Set userDepts, Set tasklists) {
		this.deptNm = deptNm;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
		this.userDepts = userDepts;
		this.tasklists = tasklists;
	}

	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	public String getDeptNm() {
		return this.deptNm;
	}

	public void setDeptNm(String deptNm) {
		this.deptNm = deptNm;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	public Set getUserDepts() {
		return this.userDepts;
	}

	public void setUserDepts(Set userDepts) {
		this.userDepts = userDepts;
	}

	public Set getTasklists() {
		return this.tasklists;
	}

	public void setTasklists(Set tasklists) {
		this.tasklists = tasklists;
	}

}
