package com.todo.model;

// Generated Jun 3, 2016 3:56:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer scheduleId;
	private TasklistAssignment tasklistAssignment;
	private Date startDttm;
	private Date endDttm;
	private String createdBy;
	private Date createdDttm;
	private String updatedBy;
	private Date updatedDttm;
	private String occurrence;
	private String status;
	private Set taskActivities = new HashSet(0);

	public Schedule() {
	}

	public Schedule(TasklistAssignment tasklistAssignment, Date startDttm, Date endDttm) {
		this.tasklistAssignment = tasklistAssignment;
		this.startDttm = startDttm;
		this.endDttm = endDttm;
	}

	public Schedule(TasklistAssignment tasklistAssignment, Date startDttm, Date endDttm, String createdBy,
			Date createdDttm, String updatedBy, Date updatedDttm, String occurrence, String status, Set taskActivities) {
		this.tasklistAssignment = tasklistAssignment;
		this.startDttm = startDttm;
		this.endDttm = endDttm;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
		this.occurrence = occurrence;
		this.status = status;
		this.taskActivities = taskActivities;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public TasklistAssignment getTasklistAssignment() {
		return this.tasklistAssignment;
	}

	public void setTasklistAssignment(TasklistAssignment tasklistAssignment) {
		this.tasklistAssignment = tasklistAssignment;
	}

	public Date getStartDttm() {
		return this.startDttm;
	}

	public void setStartDttm(Date startDttm) {
		this.startDttm = startDttm;
	}

	public Date getEndDttm() {
		return this.endDttm;
	}

	public void setEndDttm(Date endDttm) {
		this.endDttm = endDttm;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	public String getOccurrence() {
		return this.occurrence;
	}

	public void setOccurrence(String occurrence) {
		this.occurrence = occurrence;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getTaskActivities() {
		return this.taskActivities;
	}

	public void setTaskActivities(Set taskActivities) {
		this.taskActivities = taskActivities;
	}

}
