package com.todo.model;

// Generated Jun 3, 2016 3:56:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tasklist generated by hbm2java
 */
public class Tasklist implements java.io.Serializable {

	private Integer tsId;
	private Department department;
	private String tasklistNm;
	private String tasklistContent;
	private String createdBy;
	private Date createdDttm;
	private String updatedBy;
	private Date updatedDttm;
	private String lockedUser;
	private String status;
	private Set taskActivities = new HashSet(0);
	private Set tasks = new HashSet(0);
	private Set tasklistAssignments = new HashSet(0);

	public Tasklist() {
	}

	public Tasklist(Department department, String tasklistNm) {
		this.department = department;
		this.tasklistNm = tasklistNm;
	}

	public Tasklist(Department department, String tasklistNm, String tasklistContent, String createdBy,
			Date createdDttm, String updatedBy, Date updatedDttm, String lockedUser, String status, Set taskActivities,
			Set tasks, Set tasklistAssignments) {
		this.department = department;
		this.tasklistNm = tasklistNm;
		this.tasklistContent = tasklistContent;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
		this.lockedUser = lockedUser;
		this.status = status;
		this.taskActivities = taskActivities;
		this.tasks = tasks;
		this.tasklistAssignments = tasklistAssignments;
	}

	public Integer getTsId() {
		return this.tsId;
	}

	public void setTsId(Integer tsId) {
		this.tsId = tsId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getTasklistNm() {
		return this.tasklistNm;
	}

	public void setTasklistNm(String tasklistNm) {
		this.tasklistNm = tasklistNm;
	}

	public String getTasklistContent() {
		return this.tasklistContent;
	}

	public void setTasklistContent(String tasklistContent) {
		this.tasklistContent = tasklistContent;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	public String getLockedUser() {
		return this.lockedUser;
	}

	public void setLockedUser(String lockedUser) {
		this.lockedUser = lockedUser;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getTaskActivities() {
		return this.taskActivities;
	}

	public void setTaskActivities(Set taskActivities) {
		this.taskActivities = taskActivities;
	}

	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

	public Set getTasklistAssignments() {
		return this.tasklistAssignments;
	}

	public void setTasklistAssignments(Set tasklistAssignments) {
		this.tasklistAssignments = tasklistAssignments;
	}

}
