package com.todo.model;

// Generated Jun 3, 2016 3:56:09 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TaskActivity generated by hbm2java
 */
public class TaskActivity implements java.io.Serializable {

	private Integer activityId;
	private Schedule schedule;
	private Task task;
	private Tasklist tasklist;
	private User user;
	private String taskResult;
	private String taskComment;
	private String taskFile;
	private String taskAudio;
	private String taskVedio;
	private String createdBy;
	private Date createdDttm;
	private String updatedBy;
	private Date updatedDttm;

	public TaskActivity() {
	}

	public TaskActivity(Schedule schedule, Task task, Tasklist tasklist, User user) {
		this.schedule = schedule;
		this.task = task;
		this.tasklist = tasklist;
		this.user = user;
	}

	public TaskActivity(Schedule schedule, Task task, Tasklist tasklist, User user, String taskResult,
			String taskComment, String taskFile, String taskAudio, String taskVedio, String createdBy,
			Date createdDttm, String updatedBy, Date updatedDttm) {
		this.schedule = schedule;
		this.task = task;
		this.tasklist = tasklist;
		this.user = user;
		this.taskResult = taskResult;
		this.taskComment = taskComment;
		this.taskFile = taskFile;
		this.taskAudio = taskAudio;
		this.taskVedio = taskVedio;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Tasklist getTasklist() {
		return this.tasklist;
	}

	public void setTasklist(Tasklist tasklist) {
		this.tasklist = tasklist;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTaskResult() {
		return this.taskResult;
	}

	public void setTaskResult(String taskResult) {
		this.taskResult = taskResult;
	}

	public String getTaskComment() {
		return this.taskComment;
	}

	public void setTaskComment(String taskComment) {
		this.taskComment = taskComment;
	}

	public String getTaskFile() {
		return this.taskFile;
	}

	public void setTaskFile(String taskFile) {
		this.taskFile = taskFile;
	}

	public String getTaskAudio() {
		return this.taskAudio;
	}

	public void setTaskAudio(String taskAudio) {
		this.taskAudio = taskAudio;
	}

	public String getTaskVedio() {
		return this.taskVedio;
	}

	public void setTaskVedio(String taskVedio) {
		this.taskVedio = taskVedio;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
