package com.todo.model;

// Generated Jun 3, 2016 3:56:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TasklistAssignment generated by hbm2java
 */
public class TasklistAssignment implements java.io.Serializable {

	private Integer assignmentId;
	private Group group;
	private Tasklist tasklist;
	private User user;
	private String occurrence;
	private String createdBy;
	private Date createdDttm;
	private String updatedBy;
	private Date updatedDttm;
	private String status;
	private Set schedules = new HashSet(0);

	public TasklistAssignment() {
	}

	public TasklistAssignment(Tasklist tasklist, String occurrence) {
		this.tasklist = tasklist;
		this.occurrence = occurrence;
	}


	public Integer getAssignmentId() {
		return this.assignmentId;
	}

	public void setAssignmentId(Integer assignmentId) {
		this.assignmentId = assignmentId;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroups(Group group) {
		this.group = group;
	}

	public Tasklist getTasklist() {
		return this.tasklist;
	}

	public void setTasklist(Tasklist tasklist) {
		this.tasklist = tasklist;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getOccurrence() {
		return this.occurrence;
	}

	public void setOccurrence(String occurrence) {
		this.occurrence = occurrence;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Set schedules) {
		this.schedules = schedules;
	}

}
