DELIMITER //
CREATE  PROCEDURE getGroupsByDept(
	   IN p_dept_id  int)

BEGIN

 SELECT G.*, UG.USER_ID, UD.DEPT_ID FROM GROUPS G JOIN USER_GROUP UG JOIN USER_DEPT UD WHERE G.GROUP_ID = UG.GROUP_ID AND UG.USER_ID = UD.USER_ID AND G.STATUS='A' AND UD.DEPT_ID = p_dept_id;
    
END //
DELIMITER ;